### PR TITLE
ci: update to golang 1.20

### PR DESCRIPTION
**Pull request by bill-mahoney**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Issue Number:
#203 
## Sandbox Testing
Test Links :

### CODE REVIEW

**Review by ernestojeda — APPROVED** [review]
LGTM

**Comment by lenny-goodell** [comment]
@bnevis-i , Please review for the Spire minor version bump.

**Review by lenny-goodell — APPROVED** [review]
LGTM pending @bnevis-i approval

**Comment by bnevis-i** [comment]
> @bnevis-i , Please review for the Spire minor version bump.

Will review.

**Review by bnevis-i — CHANGES_REQUESTED** [review]
On hold while reviewing SPIRE version bump.

**Comment by bnevis-i** [comment]
Having trouble getting spire-server to compile with go 1.20.  Looking into it.

**Review by bnevis-i — APPROVED** [review]
LGTM with spire version left as-is.

**Pull request merged**
